### PR TITLE
proofr v0.3.0 Updates

### LINKED ISSUE #3: httr -> httr2
- `vcr` on cran only has support for `httr`, not `httr2`. `httr2` support is in the works but not ready quite yet. 
- `rcromwell` uses `vcr`. 
- which means we need to use `httr` in `rcromwell` and this pkg for now

move to `httr2` once `vcr` has support for it on github at least (& cran before `rcromwell` goes to cran)

### LINKED ISSUE #13: replace any links pointing to proof api repo with something else or remove
since proof api repo is private

### LINKED ISSUE #19: Add docs in help for securely managing authentication
In the documentation of `proof_authenticate(username, password)` we might want to include some suggestions for how to not write your hutch password as inline code as a reminder or help for newbies.

### LINKED ISSUE #22: documentation small thing - pak::pak("rcromwell")
hi,

finally started testing PROOF

on this page:  https://getwilds.org/proofr/articles/proofr.html#rcromwell-setup

there's a chunk that looks like this
```
if (!requireNamespace("rcromwell", quietly=TRUE)) {
  install.packages("pak")
  pak::pak("rcromwell")
}
```

The line `pak::pak("rcromwell")` should read `pak::pak("getwilds/rcromwell")`

Testing more now...

thanks!

Janet

### LINKED ISSUE #23: rstudio-server and the PROOF_TOKEN env
hi there,

documentation suggestion - I'm actually unclear on whether proofr is intended to be a Hutch-focussed resource or more general, so maybe this comment is too specific.

But the docs caused me brief confusion yesterday, until Dan cleared it up for me on Slack.

[This section](https://getwilds.org/proofr/articles/proofr.html#authenticate-with-the-proof-api) tells me about setting PROOF_TOKEN as an environmental variable.   But when running our Hutch Rstudio-server, R doesn't preserve most environmental variables from my generic login shell when it starts an R session, so the suggested method wasn't working. 

I had to set the token manually, until I got this advice from Dan:
"You can create a ~/.Renviron file that contains PROOF_TOKEN=your-token-here and it will be available in your RStudio Server session. For the sake of security, be sure and run chmod 0400 ~/.Renviron just to make sure only you can see its contents."

Might be good to include that advice in the proofr documentation?

thanks,

Janet

### LINKED ISSUE #24: Add to docs setting base url via env var
via https://github.com/getwilds/proofr/commit/2163061cf53166063eabb609cba50038778c802d

### PR DESCRIPTION
**Pull request by tefirman**
## Description
- Swapping `httr` for `httr2` (@sckott in [#25](https://github.com/getwilds/proofr/pull/25))
- Improving documentation (@sckott in [#27](https://github.com/getwilds/proofr/pull/27), [#28](https://github.com/getwilds/proofr/pull/28), [#29](https://github.com/getwilds/proofr/pull/29), [#30](https://github.com/getwilds/proofr/pull/30))
- Fixing linting errors identified by GitHub Action (@tefirman and @sckott in [#32](https://github.com/getwilds/proofr/pull/32))

## Related Issues
- Fixes #3 
- Fixes #19
- Fixes #13
- Fixes #22
- Fixes #23
- Fixes #24

## Testing & Examples
- See links to individual PR's listed above

### CODE REVIEW

**Comment by tefirman** [comment]
@sckott -- Could you take a look at the linting errors identified in the GitHub Actions? They're pretty minor, so I'm fine just adding `nolint` if that's easier.

**Comment by sckott** [comment]
I'll check it out

**Comment by sckott** [comment]
12a49b63b5a5c029a65f71faac455248153b239d should fix that issue, we'll see

**Review by sckott — APPROVED** [review]
Ran the shiny app locally with this dev version and did not see any issues

**Pull request merged**
